### ISSUE TITLE
Add "date" field in video details

### ISSUE THREAD

**Issue by samajammin** [efdevcon/devcon-archive#93]
Hey folks! Feature request: add "date" as a field in the video details.

e.g. on this video: https://archive.devcon.org/archive/watch/4/latest-on-ethereum/?tab=YouTube

I can see it's from Devcon 4 but it'd. be nice to know the date of the talk. Maybe within this details section:

![Image 2022-01-20 at 6 30 52 PM](https://user-images.githubusercontent.com/8097623/150455355-1e35ed0d-fcab-4bc1-9512-ef0ede937a7d.jpg)

**Comment by wslyvh** [comment]
Great suggestions! Added
